experiment_project: 'Mitty'
experiment_name: 'human2robot_finetune'
model_id:    "Wan-AI/Wan2.2-T2V-A14B-Diffusers"
output_root: '/home/guian/data/Mitty/output'
use_DiffSynth: True
use_drop_text: True
use_lora: True

training:
  resume_path: '/home/guian/data/Mitty/output/multi-view/checkpoints/step=20000.ckpt'
  batch_size: 1
  max_steps: 25000
  warmup_steps: 10
  learning_rate: 1e-5
  weight_decay: 1e-2
  save_val_interval_steps: 100
  accumulate_grad_batches: 2
  gradient_clip_val: ~
  precision: "bf16-mixed"
  accelerator: "auto"
  strategy: 'auto'
  gradient_checkpointing: True
  benchmark: False

dataset:
  video_root:  '/home/guian/data/Mitty/dataset/comparison_results_02_25/human'
  video_root2: '/home/guian/data/Mitty/dataset/comparison_results_02_25/robot'
  first_root:  ~
  is_one2three: True
  height: 480
  width: 640
  sample_n_frames: 49
  fps: 16
  num_workers: 8
  shuffle: True
  drop_last: True
  pin_memory: True
